# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AppGetHistED.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x41ppGetHistED.proto\";\n\x12\x41ppGetHistEDResDTO\x12\n\n\x02\x63p\x18\x01 \x01(\x05\x12\x0b\n\x03oft\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\r\"-\n\x0f\x41PPEnergyInfoMO\x12\n\n\x02\x65\x64\x18\x01 \x01(\r\x12\x0e\n\x06r_time\x18\x02 \x01(\r\"\\\n\x12\x41ppGetHistEDReqDTO\x12\n\n\x02sn\x18\x01 \x01(\x03\x12\x0b\n\x03oft\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\r\x12\x1f\n\x05\x65nerg\x18\x04 \x03(\x0b\x32\x10.APPEnergyInfoMOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AppGetHistED_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPGETHISTEDRESDTO']._serialized_start=22
  _globals['_APPGETHISTEDRESDTO']._serialized_end=81
  _globals['_APPENERGYINFOMO']._serialized_start=83
  _globals['_APPENERGYINFOMO']._serialized_end=128
  _globals['_APPGETHISTEDREQDTO']._serialized_start=130
  _globals['_APPGETHISTEDREQDTO']._serialized_end=222
# @@protoc_insertion_point(module_scope)
