# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AppGetHistPower.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41ppGetHistPower.proto\"m\n\x15\x41ppGetHistPowerResDTO\x12\x15\n\rcontrol_point\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x16\n\x0erequested_time\x18\x03 \x01(\r\x12\x15\n\rrequested_day\x18\x04 \x01(\r\"\xca\x02\n\x15\x41ppGetHistPowerReqDTO\x12\x15\n\rserial_number\x18\x01 \x01(\x03\x12\x14\n\x0c\x61\x63\x63\x65ss_point\x18\x02 \x01(\x05\x12\x15\n\rcontrol_point\x18\x03 \x01(\x05\x12\x0e\n\x06offset\x18\x04 \x01(\x05\x12\x14\n\x0crequest_time\x18\x05 \x01(\r\x12\x12\n\nstart_time\x18\x06 \x01(\r\x12\x17\n\x0flong_term_start\x18\x07 \x01(\r\x12\x16\n\x0e\x61\x62solute_start\x18\x08 \x01(\r\x12\x11\n\tstep_time\x18\t \x01(\r\x12\x16\n\x0erelative_power\x18\n \x01(\r\x12\x14\n\x0ctotal_energy\x18\x0b \x01(\r\x12\x14\n\x0c\x64\x61ily_energy\x18\x0c \x01(\r\x12\x13\n\x0bpower_array\x18\r \x03(\x05\x12\x16\n\x0ewarning_number\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AppGetHistPower_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPGETHISTPOWERRESDTO']._serialized_start=25
  _globals['_APPGETHISTPOWERRESDTO']._serialized_end=134
  _globals['_APPGETHISTPOWERREQDTO']._serialized_start=137
  _globals['_APPGETHISTPOWERREQDTO']._serialized_end=467
# @@protoc_insertion_point(module_scope)
