# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoSearch.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x41utoSearch.proto\"\x87\x01\n\x10\x41utoSearchReqDTO\x12\x19\n\x11\x64tu_serial_number\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x16\n\x0epackage_number\x18\x03 \x01(\x05\x12\x17\n\x0f\x63urrent_package\x18\x04 \x01(\x05\x12\x19\n\x11mi_serial_numbers\x18\x05 \x03(\x03\"n\n\x10\x41utoSearchResDTO\x12\x0f\n\x07ymd_hms\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x17\n\x0f\x63urrent_package\x18\x03 \x01(\x05\x12\x12\n\nerror_code\x18\x04 \x01(\x05\x12\x0c\n\x04time\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AutoSearch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUTOSEARCHREQDTO']._serialized_start=21
  _globals['_AUTOSEARCHREQDTO']._serialized_end=156
  _globals['_AUTOSEARCHRESDTO']._serialized_start=158
  _globals['_AUTOSEARCHRESDTO']._serialized_end=268
# @@protoc_insertion_point(module_scope)
