# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GWInfo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'GWInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cGWInfo.proto\">\n\tDevInfoMO\x12\x15\n\rserial_number\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\x05\"!\n\x03\x46MO\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c\"\xb4\x01\n\x08GWInfoMO\x12\x0b\n\x03mod\x18\x01 \x01(\x05\x12\n\n\x02sw\x18\x02 \x01(\x05\x12\n\n\x02hw\x18\x03 \x01(\x05\x12\r\n\x05\x63_mod\x18\x04 \x01(\x05\x12\x0e\n\x06wifi_v\x18\x05 \x01(\x0c\x12\x0e\n\x06gprs_v\x18\x06 \x01(\x0c\x12\x11\n\tgprs_imei\x18\x07 \x01(\x0c\x12\x0e\n\x06ka_nub\x18\x08 \x01(\x0c\x12\x0b\n\x03rid\x18\t \x01(\x05\x12\x0b\n\x03ssl\x18\n \x01(\x05\x12\x0b\n\x03\x64\x66s\x18\x0b \x01(\x03\x12\n\n\x02sv\x18\x0c \x01(\x03\"\x97\x01\n\x0cGWInfoReqDTO\x12\x15\n\rserial_number\x18\x01 \x01(\x03\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\n\n\x02\x61p\x18\x03 \x01(\x05\x12\n\n\x02\x63p\x18\x04 \x01(\x05\x12\x1a\n\x07mgwinfo\x18\x05 \x03(\x0b\x32\t.GWInfoMO\x12\x1c\n\x08mdevinfo\x18\x06 \x03(\x0b\x32\n.DevInfoMO\x12\x10\n\x02mf\x18\x07 \x03(\x0b\x32\x04.FMO\"8\n\x0cGWInfoResDTO\x12\n\n\x02\x63p\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GWInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVINFOMO']._serialized_start=16
  _globals['_DEVINFOMO']._serialized_end=78
  _globals['_FMO']._serialized_start=80
  _globals['_FMO']._serialized_end=113
  _globals['_GWINFOMO']._serialized_start=116
  _globals['_GWINFOMO']._serialized_end=296
  _globals['_GWINFOREQDTO']._serialized_start=299
  _globals['_GWINFOREQDTO']._serialized_end=450
  _globals['_GWINFORESDTO']._serialized_start=452
  _globals['_GWINFORESDTO']._serialized_end=508
# @@protoc_insertion_point(module_scope)
