# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WarnData.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WarnData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eWarnData.proto\x12#com.hoymiles_wifi.protobuf.WarnData\"\xa5\x01\n\nWarnReqDTO\x12\x0e\n\x06\x64tu_sn\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x13\n\x0bpackage_nub\x18\x03 \x01(\x05\x12\x13\n\x0bpackage_now\x18\x04 \x01(\x05\x12\x13\n\x0bwarn_device\x18\x05 \x01(\x05\x12:\n\x05warns\x18\x06 \x03(\x0b\x32+.com.hoymiles_wifi.protobuf.WarnData.WarnMO\"t\n\x06WarnMO\x12\r\n\x05pv_sn\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03num\x18\x03 \x01(\x05\x12\x0e\n\x06s_time\x18\x04 \x01(\x05\x12\x0e\n\x06\x65_time\x18\x05 \x01(\x05\x12\x0f\n\x07w_data1\x18\x06 \x01(\x05\x12\x0f\n\x07w_data2\x18\x07 \x01(\x05\"b\n\nWarnResDTO\x12\x0f\n\x07ymd_hms\x18\x01 \x01(\t\x12\x13\n\x0bpackage_now\x18\x02 \x01(\x05\x12\x10\n\x08\x65rr_code\x18\x03 \x01(\x05\x12\x0e\n\x06offset\x18\x04 \x01(\x05\x12\x0c\n\x04time\x18\x05 \x01(\x05\"\xc3\x01\n\nWaveReqDTO\x12\x0e\n\x06\x64tu_sn\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x13\n\x0bpackage_nub\x18\x03 \x01(\x05\x12\x13\n\x0bpackage_now\x18\x04 \x01(\x05\x12\r\n\x05pv_sn\x18\x05 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x06 \x01(\x05\x12\x0b\n\x03num\x18\x07 \x01(\x05\x12\x11\n\twarn_time\x18\x08 \x01(\x05\x12\x10\n\x08\x64\x61ta_len\x18\t \x01(\x05\x12\x0b\n\x03pos\x18\n \x01(\x05\x12\x11\n\twarn_data\x18\x0b \x01(\t\"b\n\nWaveResDTO\x12\x0f\n\x07ymd_hms\x18\x01 \x01(\t\x12\x13\n\x0bpackage_now\x18\x02 \x01(\x05\x12\x10\n\x08\x65rr_code\x18\x03 \x01(\x05\x12\x0e\n\x06offset\x18\x04 \x01(\x05\x12\x0c\n\x04time\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WarnData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WARNREQDTO']._serialized_start=56
  _globals['_WARNREQDTO']._serialized_end=221
  _globals['_WARNMO']._serialized_start=223
  _globals['_WARNMO']._serialized_end=339
  _globals['_WARNRESDTO']._serialized_start=341
  _globals['_WARNRESDTO']._serialized_end=439
  _globals['_WAVEREQDTO']._serialized_start=442
  _globals['_WAVEREQDTO']._serialized_end=637
  _globals['_WAVERESDTO']._serialized_start=639
  _globals['_WAVERESDTO']._serialized_end=737
# @@protoc_insertion_point(module_scope)
